"""Regenerate the frontend's mock catalog from the real one.

`frontend/src/api/mockCatalog.ts` is a snapshot of `backend/data/catalog.json`
that mock mode serves when there is no backend — which is every deployed
build, since the kiosk frontend deploys to static hosting on its own. That
makes the snapshot shopper-visible, not a test fixture, and a stale one is
not obviously stale: the images come from the backend's `/garments/` paths
by id, so when the catalog was re-sourced the frontend went on showing the
OLD names and prices against the NEW photos. A green knit tank dress was
labelled "Brown Animal Print Dress" at EUR 1650 — the price still in rupees
from the dataset the first catalog was built from.

The snapshot was documented as "regenerate after editing the catalog" and
regenerated by hand, which is exactly the step that got skipped. This script
is that step, so it can be run rather than remembered:

    python3 scripts/sync_mock_catalog.py            # rewrite the snapshot
    python3 scripts/sync_mock_catalog.py --check    # fail if it's stale

`--check` exits non-zero when the file on disk differs from what the catalog
would produce, so CI (or a pre-commit hook) can refuse a catalog edit that
leaves the snapshot behind.

Only the fields `/recommend` actually returns are emitted — the scoring
fields (`color_lab`, `silhouette`) stay server-side, where the scoring is.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

BACKEND = Path(__file__).resolve().parent.parent
CATALOG = BACKEND / "data" / "catalog.json"
SNAPSHOT = BACKEND.parent / "frontend" / "src" / "api" / "mockCatalog.ts"

# Exactly the Garment fields the API returns, plus the two tag arrays the
# fitting room's filters run against. Order is the emitted key order.
FIELDS = ("id", "name", "category", "image_url", "price", "location",
          "sizes_in_stock", "buy_url", "color_hex")
TAG_FIELDS = ("season_tags", "occasion_tags")

HEADER = '''import type { Garment } from "./types";

/**
 * A snapshot of the store's real catalog (backend/data/catalog.json), used
 * only by mock mode.
 *
 * Mock mode exists so the kiosk's screens can be worked on without the
 * backend or the ML pipeline — but a rack of invented placeholder garments
 * makes the fitting room useless for exactly the design questions mock mode
 * is meant to answer (do real product photos crop well, do real names fit
 * on a card, does a real catalog leave the filters looking empty). So these
 * are the actual garments, with the real season and occasion tags the
 * filters run against.
 *
 * GENERATED — do not hand-edit. Regenerate after any catalog change:
 *
 *     cd backend && python3 scripts/sync_mock_catalog.py
 *
 * Hand-editing is what let this file go stale once already: the catalog was
 * re-sourced, this snapshot wasn't, and mock mode showed the previous
 * catalog's names and prices against the new photos.
 *
 * `image_url` stays a backend-relative path, exactly as the API returns it,
 * so `resolveImageUrl` handles it identically in both modes.
 */
export interface MockGarment extends Garment {
  season_tags: string[];
  occasion_tags: string[];
}

export const MOCK_CATALOG: MockGarment[] = [
'''


def ts_value(value) -> str:
    """A JSON scalar/array as the TypeScript literal for it."""
    return json.dumps(value, ensure_ascii=False)


def render(catalog: list[dict]) -> str:
    lines = [HEADER]
    for garment in catalog:
        missing = [f for f in FIELDS if f not in garment]
        if missing:
            raise SystemExit(
                f"{garment.get('id', '?')} is missing {', '.join(missing)} — "
                f"the snapshot must carry every field /recommend returns."
            )
        head = ", ".join(f"{f}: {ts_value(garment[f])}" for f in FIELDS[:5])
        tail = ", ".join(f"{f}: {ts_value(garment[f])}" for f in FIELDS[5:])
        tags = ", ".join(f"{f}: {ts_value(garment.get(f, []))}" for f in TAG_FIELDS)
        lines.append(f"  {{ {head},\n    {tail},\n    {tags} }},\n")
    lines.append("];\n")
    return "".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the snapshot is out of date, and write nothing")
    args = parser.parse_args()

    catalog = json.loads(CATALOG.read_text())
    generated = render(catalog)
    current = SNAPSHOT.read_text() if SNAPSHOT.exists() else ""

    if args.check:
        if generated != current:
            print(f"STALE: {SNAPSHOT.relative_to(BACKEND.parent)} does not match "
                  f"{CATALOG.relative_to(BACKEND.parent)}.\n"
                  f"Run: cd backend && python3 scripts/sync_mock_catalog.py",
                  file=sys.stderr)
            sys.exit(1)
        print(f"up to date — {len(catalog)} garments")
        return

    SNAPSHOT.write_text(generated)
    prices = [g["price"] for g in catalog]
    print(f"wrote {SNAPSHOT.relative_to(BACKEND.parent)}: {len(catalog)} garments, "
          f"prices {min(prices)}–{max(prices)}")


if __name__ == "__main__":
    main()
