import type { Garment } from "./types";

/**
 * A snapshot of the store's real catalog (backend/data/catalog.json), used
 * only by mock mode.
 *
 * Mock mode exists so the kiosk's screens can be worked on without the
 * backend or the ML pipeline — but a rack of invented placeholder garments
 * makes the fitting room useless for exactly the design questions mock mode
 * is meant to answer (do real product photos crop well, do real names fit
 * on a card, does a real catalog leave the filters looking empty). So these
 * are the actual garments, with the real season and occasion tags the
 * filters run against.
 *
 * GENERATED — do not hand-edit. Regenerate after any catalog change:
 *
 *     cd backend && python3 scripts/sync_mock_catalog.py
 *
 * Hand-editing is what let this file go stale once already: the catalog was
 * re-sourced, this snapshot wasn't, and mock mode showed the previous
 * catalog's names and prices against the new photos.
 *
 * `image_url` stays a backend-relative path, exactly as the API returns it,
 * so `resolveImageUrl` handles it identically in both modes.
 */
export interface MockGarment extends Garment {
  season_tags: string[];
  occasion_tags: string[];
}

export const MOCK_CATALOG: MockGarment[] = [
  { id: "d1", name: "Ribbed Knit Mini Tank Dress", category: "dress", image_url: "/garments/d1.jpg", price: 39,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#266455",
    season_tags: ["winter", "autumn"], occasion_tags: ["work", "date night", "everyday"] },
  { id: "d2", name: "Sleeveless Knit A-Line Midi Dress", category: "dress", image_url: "/garments/d2.jpg", price: 59,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#151519",
    season_tags: ["winter", "summer"], occasion_tags: ["date night", "everyday"] },
  { id: "d3", name: "Bubble Hem Mini Dress", category: "dress", image_url: "/garments/d3.jpg", price: 52,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#E8EAE9",
    season_tags: ["summer"], occasion_tags: ["work", "wedding guest", "everyday"] },
  { id: "d4", name: "Ditsy Print Collared Midi Dress", category: "dress", image_url: "/garments/d4.jpg", price: 58,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#143968",
    season_tags: ["winter"], occasion_tags: ["wedding guest", "everyday"] },
  { id: "d5", name: "Tie-Strap Ruched Mini Dress", category: "dress", image_url: "/garments/d5.jpg", price: 54,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#E2DDC6",
    season_tags: ["spring", "autumn"], occasion_tags: ["wedding guest", "everyday"] },
  { id: "d6", name: "Balloon Hem Midi Dress", category: "dress", image_url: "/garments/d6.jpg", price: 68,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#5C5368",
    season_tags: ["winter", "summer"], occasion_tags: ["everyday"] },
  { id: "d7", name: "Tiered Shirt Dress", category: "dress", image_url: "/garments/d7.jpg", price: 72,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#C6AA89",
    season_tags: ["spring", "autumn"], occasion_tags: ["work", "everyday"] },
  { id: "d8", name: "Satin Slip Midi Dress", category: "dress", image_url: "/garments/d8.jpg", price: 64,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#D3CCC6",
    season_tags: ["summer"], occasion_tags: ["wedding guest", "everyday"] },
  { id: "d9", name: "Poplin Shirt Dress", category: "dress", image_url: "/garments/d9.jpg", price: 66,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#8A95A6",
    season_tags: ["summer"], occasion_tags: ["work", "everyday"] },
  { id: "d10", name: "Belted Wrap Coat Dress", category: "dress", image_url: "/garments/d10.jpg", price: 79,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#171617",
    season_tags: ["winter", "summer"], occasion_tags: ["work", "everyday"] },
  { id: "d11", name: "Draped Neck Column Midi Dress", category: "dress", image_url: "/garments/d11.jpg", price: 55,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#E4C8C3",
    season_tags: ["summer", "spring"], occasion_tags: ["work", "wedding guest", "everyday"] },
  { id: "d12", name: "Floral Satin Slip Midi Dress", category: "dress", image_url: "/garments/d12.jpg", price: 61,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#586547",
    season_tags: ["autumn"], occasion_tags: ["everyday"] },
  { id: "d13", name: "Puff Sleeve Tiered Midi Dress", category: "dress", image_url: "/garments/d13.jpg", price: 57,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#4888C8",
    season_tags: ["winter"], occasion_tags: ["wedding guest", "everyday"] },
  { id: "d14", name: "Sleeveless A-Line Mini Dress", category: "dress", image_url: "/garments/d14.jpg", price: 47,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#CAB9C4",
    season_tags: ["summer"], occasion_tags: ["work", "everyday"] },
  { id: "d15", name: "Puff Sleeve Ruffle Mini Dress", category: "dress", image_url: "/garments/d15.jpg", price: 63,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#E5C7CB",
    season_tags: ["summer"], occasion_tags: ["wedding guest", "everyday"] },
  { id: "d16", name: "Pleated Midi Dress", category: "dress", image_url: "/garments/d16.jpg", price: 74,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#161A23",
    season_tags: ["winter"], occasion_tags: ["work", "everyday"] },
  { id: "d17", name: "Striped Belted Shirt Dress", category: "dress", image_url: "/garments/d17.jpg", price: 69,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#D5D9E9",
    season_tags: ["summer"], occasion_tags: ["work", "wedding guest", "everyday"] },
  { id: "d18", name: "Striped Ruffle Hem Mini Dress", category: "dress", image_url: "/garments/d18.jpg", price: 43,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#B5B6B9",
    season_tags: ["summer"], occasion_tags: ["everyday"] },
  { id: "d19", name: "Houndstooth Cami Midi Dress", category: "dress", image_url: "/garments/d19.jpg", price: 56,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#282829",
    season_tags: ["winter", "summer"], occasion_tags: ["work", "date night", "everyday"] },
  { id: "d20", name: "Floral Cami Midi Dress", category: "dress", image_url: "/garments/d20.jpg", price: 49,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#999489",
    season_tags: ["autumn", "summer"], occasion_tags: ["everyday"] },
  { id: "d21", name: "Rib Knit Cami Midi Dress", category: "dress", image_url: "/garments/d21.jpg", price: 45,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#A5B8AA",
    season_tags: ["summer", "autumn"], occasion_tags: ["work", "everyday"] },
  { id: "d22", name: "Puff Sleeve A-Line Dress", category: "dress", image_url: "/garments/d22.jpg", price: 51,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#E0D5AC",
    season_tags: ["spring"], occasion_tags: ["work", "wedding guest", "everyday"] },
  { id: "d23", name: "Draped Slip Midi Dress", category: "dress", image_url: "/garments/d23.jpg", price: 65,
    location: "Women's · Aisle 3 · Dresses", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#C6C3B9",
    season_tags: ["summer", "autumn"], occasion_tags: ["wedding guest", "everyday"] },
  { id: "t1", name: "Cropped Graphic Sweatshirt", category: "top", image_url: "/garments/t1.jpg", price: 32,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#1A1A1B",
    season_tags: ["winter", "summer"], occasion_tags: ["date night", "everyday"] },
  { id: "t2", name: "Cable Knit Cricket Jumper", category: "top", image_url: "/garments/t2.jpg", price: 45,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#F8F4EA",
    season_tags: ["summer"], occasion_tags: ["everyday"] },
  { id: "t3", name: "Brushed Wool Crewneck Jumper", category: "top", image_url: "/garments/t3.jpg", price: 42,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#046A35",
    season_tags: ["spring", "autumn"], occasion_tags: ["everyday"] },
  { id: "t4", name: "Mohair Stripe Knit Jumper", category: "top", image_url: "/garments/t4.jpg", price: 47,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#17334A",
    season_tags: ["winter"], occasion_tags: ["everyday"] },
  { id: "t5", name: "Pigment Dyed Hoodie", category: "top", image_url: "/garments/t5.jpg", price: 38,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#ECA3CC",
    season_tags: ["summer", "winter"], occasion_tags: ["date night", "everyday"] },
  { id: "t6", name: "Boxy Logo T-Shirt", category: "top", image_url: "/garments/t6.jpg", price: 19,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#E3AA4C",
    season_tags: ["spring"], occasion_tags: ["date night", "everyday"] },
  { id: "t7", name: "Fine Knit Button Cardigan", category: "top", image_url: "/garments/t7.jpg", price: 41,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#911B19",
    season_tags: ["spring", "autumn"], occasion_tags: ["date night", "everyday"] },
  { id: "t8", name: "Washed Graphic Hoodie", category: "top", image_url: "/garments/t8.jpg", price: 36,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#765B64",
    season_tags: ["winter", "summer"], occasion_tags: ["everyday"] },
  { id: "t9", name: "Ribbed Short Sleeve Knit Top", category: "top", image_url: "/garments/t9.jpg", price: 27,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#1A1A18",
    season_tags: ["winter", "autumn"], occasion_tags: ["everyday"] },
  { id: "t10", name: "Pinstripe Oversized Shirt", category: "top", image_url: "/garments/t10.jpg", price: 34,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#D9D9D7",
    season_tags: ["summer"], occasion_tags: ["work", "everyday"] },
  { id: "t11", name: "Short Sleeve Camp Shirt", category: "top", image_url: "/garments/t11.jpg", price: 29,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#55623D",
    season_tags: ["autumn"], occasion_tags: ["work", "everyday"] },
  { id: "t12", name: "Gingham Short Sleeve Shirt", category: "top", image_url: "/garments/t12.jpg", price: 31,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#D8C5B7",
    season_tags: ["autumn", "spring"], occasion_tags: ["work", "everyday"] },
  { id: "t13", name: "Lace Trim Rib Camisole", category: "top", image_url: "/garments/t13.jpg", price: 22,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#BAB8B4",
    season_tags: ["summer"], occasion_tags: ["work", "everyday"] },
  { id: "t14", name: "Poplin Short Sleeve Shirt", category: "top", image_url: "/garments/t14.jpg", price: 28,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#B3ABD4",
    season_tags: ["summer"], occasion_tags: ["work", "everyday"] },
  { id: "t15", name: "Ribbed Tank Top", category: "top", image_url: "/garments/t15.jpg", price: 18,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#C42A1A",
    season_tags: ["spring"], occasion_tags: ["everyday"] },
  { id: "t16", name: "Wool Blend Knit Cardigan", category: "top", image_url: "/garments/t16.jpg", price: 52,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#384646",
    season_tags: ["winter", "summer"], occasion_tags: ["everyday"] },
  { id: "t17", name: "Striped Mohair Jumper", category: "top", image_url: "/garments/t17.jpg", price: 44,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#D9C7B7",
    season_tags: ["spring", "autumn"], occasion_tags: ["everyday"] },
  { id: "t18", name: "Breton Stripe Long Sleeve Tee", category: "top", image_url: "/garments/t18.jpg", price: 26,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#E6E2D9",
    season_tags: ["summer"], occasion_tags: ["everyday"] },
  { id: "t19", name: "Knit Polo Top", category: "top", image_url: "/garments/t19.jpg", price: 39,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#E2D2B8",
    season_tags: ["spring"], occasion_tags: ["everyday"] },
  { id: "t20", name: "Fine Knit Roll Neck", category: "top", image_url: "/garments/t20.jpg", price: 33,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#A5A5A9",
    season_tags: ["summer"], occasion_tags: ["work", "everyday"] },
  { id: "t21", name: "Ribbed High Neck Sleeveless Top", category: "top", image_url: "/garments/t21.jpg", price: 24,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#141819",
    season_tags: ["winter", "summer"], occasion_tags: ["everyday"] },
  { id: "t22", name: "Ribbon Tie Baby Tee", category: "top", image_url: "/garments/t22.jpg", price: 21,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#F1E4ED",
    season_tags: ["summer"], occasion_tags: ["everyday"] },
  { id: "t23", name: "Oversized Graphic Sweatshirt", category: "top", image_url: "/garments/t23.jpg", price: 37,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#362A26",
    season_tags: ["autumn", "winter"], occasion_tags: ["date night", "everyday"] },
  { id: "t24", name: "Short Sleeve Knit Polo", category: "top", image_url: "/garments/t24.jpg", price: 35,
    location: "Women's · Aisle 2 · Tops", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#2B3B54",
    season_tags: ["winter"], occasion_tags: ["everyday"] },
  { id: "p1", name: "Tailored Wide Leg Trousers", category: "pants", image_url: "/garments/p1.jpg", price: 58,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#39383A",
    season_tags: ["winter", "summer"], occasion_tags: ["work", "everyday"] },
  { id: "p2", name: "Pleated Corduroy Trousers", category: "pants", image_url: "/garments/p2.jpg", price: 49,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#A58A67",
    season_tags: ["autumn", "spring"], occasion_tags: ["work", "everyday"] },
  { id: "p3", name: "Balloon Leg Jeans", category: "pants", image_url: "/garments/p3.jpg", price: 62,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#172537",
    season_tags: ["winter"], occasion_tags: ["work", "everyday"] },
  { id: "p4", name: "Cotton Twill Straight Trousers", category: "pants", image_url: "/garments/p4.jpg", price: 46,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#596453",
    season_tags: ["autumn"], occasion_tags: ["work", "everyday"] },
  { id: "p5", name: "Pleated Wide Chinos", category: "pants", image_url: "/garments/p5.jpg", price: 52,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#A49A8B",
    season_tags: ["autumn"], occasion_tags: ["work", "everyday"] },
  { id: "p6", name: "Rigid Denim Straight Jeans", category: "pants", image_url: "/garments/p6.jpg", price: 67,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#262736",
    season_tags: ["winter"], occasion_tags: ["work", "everyday"] },
  { id: "p7", name: "Pleated Wide Leg Trousers", category: "pants", image_url: "/garments/p7.jpg", price: 54,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#413C39",
    season_tags: ["autumn", "winter"], occasion_tags: ["work", "everyday"] },
  { id: "p8", name: "Wide Leg Ecru Jeans", category: "pants", image_url: "/garments/p8.jpg", price: 59,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#EBE8E3",
    season_tags: ["summer"], occasion_tags: ["work", "everyday"] },
  { id: "p9", name: "Washed Baggy Jeans", category: "pants", image_url: "/garments/p9.jpg", price: 63,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#29282B",
    season_tags: ["winter", "summer"], occasion_tags: ["work", "everyday"] },
  { id: "p10", name: "Tartan Check Trousers", category: "pants", image_url: "/garments/p10.jpg", price: 48,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#253538",
    season_tags: ["winter"], occasion_tags: ["work", "everyday"] },
  { id: "p11", name: "Stonewash Wide Jeans", category: "pants", image_url: "/garments/p11.jpg", price: 57,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#545B63",
    season_tags: ["winter", "summer"], occasion_tags: ["work", "everyday"] },
  { id: "p12", name: "Parachute Cargo Trousers", category: "pants", image_url: "/garments/p12.jpg", price: 44,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#7B6A74",
    season_tags: ["summer", "winter"], occasion_tags: ["everyday"] },
  { id: "p13", name: "Drawstring Wide Trousers", category: "pants", image_url: "/garments/p13.jpg", price: 51,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#774847",
    season_tags: ["autumn"], occasion_tags: ["everyday"] },
  { id: "p14", name: "Parachute Trousers", category: "pants", image_url: "/garments/p14.jpg", price: 45,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#372426",
    season_tags: ["winter", "autumn"], occasion_tags: ["everyday"] },
  { id: "p15", name: "Straight Leg Wool Trousers", category: "pants", image_url: "/garments/p15.jpg", price: 56,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#46474A",
    season_tags: ["winter", "summer"], occasion_tags: ["work", "everyday"] },
  { id: "p16", name: "Balloon Leg Cargo Trousers", category: "pants", image_url: "/garments/p16.jpg", price: 50,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#676448",
    season_tags: ["autumn"], occasion_tags: ["everyday"] },
  { id: "p17", name: "Wide Leg Utility Trousers", category: "pants", image_url: "/garments/p17.jpg", price: 53,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#3C332A",
    season_tags: ["autumn"], occasion_tags: ["work", "everyday"] },
  { id: "p18", name: "Wide Leg Twill Trousers", category: "pants", image_url: "/garments/p18.jpg", price: 55,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#DCD4C9",
    season_tags: ["summer", "spring"], occasion_tags: ["work", "everyday"] },
  { id: "p19", name: "Corduroy Straight Trousers", category: "pants", image_url: "/garments/p19.jpg", price: 61,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#262636",
    season_tags: ["winter"], occasion_tags: ["work", "everyday"] },
  { id: "p20", name: "Camo Print Cargo Trousers", category: "pants", image_url: "/garments/p20.jpg", price: 47,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#54473A",
    season_tags: ["autumn"], occasion_tags: ["work", "everyday"] },
  { id: "p21", name: "Distressed Wide Jeans", category: "pants", image_url: "/garments/p21.jpg", price: 64,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#343A47",
    season_tags: ["winter"], occasion_tags: ["work", "everyday"] },
  { id: "p22", name: "Cotton Jogger Trousers", category: "pants", image_url: "/garments/p22.jpg", price: 42,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#1C1C1C",
    season_tags: ["winter", "summer"], occasion_tags: ["everyday"] },
  { id: "p23", name: "Pleated Camel Trousers", category: "pants", image_url: "/garments/p23.jpg", price: 57,
    location: "Women's · Aisle 5 · Trousers", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#A99567",
    season_tags: ["spring", "autumn"], occasion_tags: ["work", "everyday"] },
];
