import type { Garment } from "./types";

/**
 * A snapshot of the store's real catalog (backend/data/catalog.json), used
 * only by mock mode.
 *
 * Mock mode exists so the kiosk's screens can be worked on without the
 * backend or the ML pipeline — but a rack of invented placeholder garments
 * makes the fitting room useless for exactly the design questions mock mode
 * is meant to answer (do real product photos crop well, do real names fit
 * on a card, does a real 40-piece catalog leave the filters looking empty).
 * So these are the actual garments, with the real season and occasion tags
 * the filters run against.
 *
 * Regenerate after editing the catalog:
 *   python3 -c "import json;print(len(json.load(open('backend/data/catalog.json'))))"
 * and re-run the snapshot step in this file's git history — or simply hand-
 * edit, since the only fields here are the ones /recommend returns.
 *
 * `image_url` stays a backend-relative path, exactly as the API returns it,
 * so `resolveImageUrl` handles it identically in both modes.
 */
export interface MockGarment extends Garment {
  season_tags: string[];
  occasion_tags: string[];
}

export const MOCK_CATALOG: MockGarment[] = [
  { id: "d1", name: "Brown Animal Print Dress", category: "dress", image_url: "/garments/d1.jpg", price: 1650,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#31302E",
    season_tags: ["winter", "autumn"], occasion_tags: ["date night", "everyday"] },
  { id: "d2", name: "Blue Dress", category: "dress", image_url: "/garments/d2.jpg", price: 1910,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#1C2245",
    season_tags: ["winter"], occasion_tags: ["date night", "everyday"] },
  { id: "d3", name: "Navy Blue Printed Dress", category: "dress", image_url: "/garments/d3.jpg", price: 1280,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#24252F",
    season_tags: ["winter"], occasion_tags: ["date night", "everyday"] },
  { id: "d4", name: "Yellow Dotted Print Dress", category: "dress", image_url: "/garments/d4.jpg", price: 1790,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#FDF970",
    season_tags: ["spring"], occasion_tags: ["date night", "wedding guest"] },
  { id: "d5", name: "Tonga Olive Dress", category: "dress", image_url: "/garments/d5.jpg", price: 2210,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#908E86",
    season_tags: ["summer", "autumn"], occasion_tags: ["everyday"] },
  { id: "d6", name: "Black Dress", category: "dress", image_url: "/garments/d6.jpg", price: 1980,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#19191A",
    season_tags: ["winter", "summer"], occasion_tags: ["date night", "everyday"] },
  { id: "d7", name: "Black & Purple Dress", category: "dress", image_url: "/garments/d7.jpg", price: 2160,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#828392",
    season_tags: ["summer"], occasion_tags: ["everyday"] },
  { id: "d8", name: "Grey Melange Dress", category: "dress", image_url: "/garments/d8.jpg", price: 1730,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#45454F",
    season_tags: ["winter"], occasion_tags: ["date night", "everyday"] },
  { id: "d9", name: "Off White Dress", category: "dress", image_url: "/garments/d9.jpg", price: 2130,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#DBD8D2",
    season_tags: ["summer"], occasion_tags: ["wedding guest", "everyday"] },
  { id: "d10", name: "Magenta Dress", category: "dress", image_url: "/garments/d10.jpg", price: 2070,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#851C5B",
    season_tags: ["winter"], occasion_tags: ["date night", "wedding guest"] },
  { id: "d11", name: "Teal Dress", category: "dress", image_url: "/garments/d11.jpg", price: 1330,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#1B393A",
    season_tags: ["winter"], occasion_tags: ["date night", "everyday"] },
  { id: "d12", name: "GeoPrint Multi Coloured Dress", category: "dress", image_url: "/garments/d12.jpg", price: 1070,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#F8FECF",
    season_tags: ["spring"], occasion_tags: ["everyday"] },
  { id: "d13", name: "Blossom Silk Cream Dress", category: "dress", image_url: "/garments/d13.jpg", price: 1610,
    location: "Women's \u00b7 Aisle 3 \u00b7 Dresses", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#FED9D2",
    season_tags: ["spring", "summer"], occasion_tags: ["wedding guest", "everyday"] },
  { id: "t1", name: "Multicoloured Printed Tunic", category: "top", image_url: "/garments/t1.jpg", price: 750,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#B0D0B1",
    season_tags: ["spring"], occasion_tags: ["everyday"] },
  { id: "t2", name: "Peach Kaftan Top", category: "top", image_url: "/garments/t2.jpg", price: 1210,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#A5A3A4",
    season_tags: ["summer"], occasion_tags: ["work", "everyday"] },
  { id: "t3", name: "Cream Tunic", category: "top", image_url: "/garments/t3.jpg", price: 700,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#E4DCD8",
    season_tags: ["summer"], occasion_tags: ["everyday"] },
  { id: "t4", name: "Elle Teal T-shirt", category: "top", image_url: "/garments/t4.jpg", price: 820,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#185163",
    season_tags: ["winter"], occasion_tags: ["everyday"] },
  { id: "t5", name: "Printed Mauve Top", category: "top", image_url: "/garments/t5.jpg", price: 840,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#3C2D39",
    season_tags: ["winter"], occasion_tags: ["work", "date night", "everyday"] },
  { id: "t6", name: "Khaki Tunic", category: "top", image_url: "/garments/t6.jpg", price: 640,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#DBD9DB",
    season_tags: ["summer"], occasion_tags: ["everyday"] },
  { id: "t7", name: "Mustard Yellow Top", category: "top", image_url: "/garments/t7.jpg", price: 560,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#F0CF6F",
    season_tags: ["spring"], occasion_tags: ["date night", "everyday"] },
  { id: "t8", name: "Printed Dark Brown Top", category: "top", image_url: "/garments/t8.jpg", price: 510,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#322E2E",
    season_tags: ["winter", "autumn"], occasion_tags: ["work", "date night", "everyday"] },
  { id: "t9", name: "Bella Yellow Top", category: "top", image_url: "/garments/t9.jpg", price: 1260,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#EED96F",
    season_tags: ["spring"], occasion_tags: ["date night", "everyday"] },
  { id: "t10", name: "W Tan Kurti", category: "top", image_url: "/garments/t10.jpg", price: 580,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#E3C4B1",
    season_tags: ["spring", "autumn"], occasion_tags: ["work", "everyday"] },
  { id: "t11", name: "Printed Green T-shirt", category: "top", image_url: "/garments/t11.jpg", price: 540,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#BBFAB9",
    season_tags: ["spring"], occasion_tags: ["date night", "everyday"] },
  { id: "t12", name: "Femella Gold Shirt", category: "top", image_url: "/garments/t12.jpg", price: 460,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#D8D2BC",
    season_tags: ["spring", "autumn"], occasion_tags: ["work", "everyday"] },
  { id: "t13", name: "Coffee Brown T-shirt", category: "top", image_url: "/garments/t13.jpg", price: 1020,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#2E2526",
    season_tags: ["winter", "autumn"], occasion_tags: ["date night", "everyday"] },
  { id: "t14", name: "Tank Blue T-shirt", category: "top", image_url: "/garments/t14.jpg", price: 490,
    location: "Women's \u00b7 Aisle 2 \u00b7 Tops", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#7BEDFD",
    season_tags: ["summer"], occasion_tags: ["date night", "everyday"] },
  { id: "p1", name: "Lavender Magic Colour Jeans", category: "pants", image_url: "/garments/p1.jpg", price: 1530,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#DCD8E6",
    season_tags: ["summer"], occasion_tags: ["work", "everyday"] },
  { id: "p2", name: "Aneri Grey Leggings", category: "pants", image_url: "/garments/p2.jpg", price: 1400,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#E2E1E4",
    season_tags: ["summer"], occasion_tags: ["everyday"] },
  { id: "p3", name: "Navy Cotton Stretch Leggings", category: "pants", image_url: "/garments/p3.jpg", price: 770,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#181825",
    season_tags: ["winter"], occasion_tags: ["everyday"] },
  { id: "p4", name: "Magenta Leggings", category: "pants", image_url: "/garments/p4.jpg", price: 1450,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["XS", "S", "M", "L", "XL"], buy_url: "#", color_hex: "#792348",
    season_tags: ["winter"], occasion_tags: ["everyday"] },
  { id: "p5", name: "Brown Trousers", category: "pants", image_url: "/garments/p5.jpg", price: 1070,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#221B19",
    season_tags: ["autumn", "winter"], occasion_tags: ["work", "everyday"] },
  { id: "p6", name: "Cream Trousers", category: "pants", image_url: "/garments/p6.jpg", price: 1470,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#DCD7C5",
    season_tags: ["spring", "autumn"], occasion_tags: ["work", "everyday"] },
  { id: "p7", name: "Teal Skinny Leggings", category: "pants", image_url: "/garments/p7.jpg", price: 1200,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["S", "M", "L", "XL"], buy_url: "#", color_hex: "#1B6798",
    season_tags: ["winter"], occasion_tags: ["everyday"] },
  { id: "p8", name: "ONLY Peach Jeans", category: "pants", image_url: "/garments/p8.jpg", price: 1550,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#E6B1B8",
    season_tags: ["summer", "spring"], occasion_tags: ["work", "everyday"] },
  { id: "p9", name: "Turquoise Blue Leggings", category: "pants", image_url: "/garments/p9.jpg", price: 640,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#0DD0CF",
    season_tags: ["summer", "winter"], occasion_tags: ["everyday"] },
  { id: "p10", name: "ONLY Orange Trousers", category: "pants", image_url: "/garments/p10.jpg", price: 1140,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#F93C25",
    season_tags: ["spring"], occasion_tags: ["everyday"] },
  { id: "p11", name: "Solid Blue Leggings", category: "pants", image_url: "/garments/p11.jpg", price: 1370,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["S", "M", "L"], buy_url: "#", color_hex: "#10BCCD",
    season_tags: ["winter", "summer"], occasion_tags: ["everyday"] },
  { id: "p12", name: "Mauve Track Pant", category: "pants", image_url: "/garments/p12.jpg", price: 1110,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["XS", "S", "M", "L"], buy_url: "#", color_hex: "#715A64",
    season_tags: ["winter", "summer"], occasion_tags: ["everyday"] },
  { id: "p13", name: "Aza Blue Jeans", category: "pants", image_url: "/garments/p13.jpg", price: 1240,
    location: "Women's \u00b7 Aisle 5 \u00b7 Pants", sizes_in_stock: ["XS", "S", "M"], buy_url: "#", color_hex: "#9BB0C4",
    season_tags: ["summer"], occasion_tags: ["work", "everyday"] },
];
